name: Terraform Azure Deploy

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_SECRETS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: ./platform
      run: terraform init

    - name: Terraform Validate
      working-directory: ./platform
      run: terraform validate

    - name: Terraform Plan
      working-directory: ./platform
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      working-directory: ./platform
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
